# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-19 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picdirectory',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/diseaseImage'),
            preserve_default=False,
        ),
    ]
